config/routes.rb
Rails.application.routes.draw do
  resources :student_ambassadors
  match 'sa', to: 'student_ambassadors#new', via: :get

  ActiveAdmin.routes(self)
  #devise_for :users , controllers: {registrations: 'users/registrations',
   #                                 passwords:     'users/passwords'
    #                                }
  # mondblogger
  mount MongodbLogger::Server.new, at: "/logs"

  get 'pages/home'
  get 'pages/navbar'
  
  match 'stats', to: 'pages#stats', via: :get
  match 'privacypolicy', to: 'pages#privacypolicy', via: :get

  resources :classifieds do
    member do
      post :contact_seller
      post :booth_pickup
    end
  end
  
  resources :users

   root to: 'classifieds#index'
  # root to: 'pages#home'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get], as: 'auth_callback'
  match 'auth/failure', to: redirect('/'), via: [:post, :get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]




  # autocomplete on form
  get '/classifieds/autocomplete/' => 'classifieds#autocomplete'

  # current state
  get '/state/' => 'application#state'

end

app/models/classified.rb
class Classified < ActiveRecord::Base
  searchkick settings: {number_of_shards: 1}
  
  enum listing_type: { buy: 0, sell: 1 }

  has_many :orders
  belongs_to :user
  accepts_nested_attributes_for :user
  belongs_to :college
  belongs_to :category

  include HasToken
  has_token
  
  mount_uploader :image, ImageUploader
  
  scope :sold, -> { where(sold: true) }
  scope :spam, -> { where(spam: true) }
  scope :unlisted, -> { where(list: false) }
  scope :deleted, -> { where(deleted: true) }
 
  def owner
    user
  end
  
  def owner?(user)
    owner == user
  end
  
  def delete!
    self.deleted = true
    save
  end
  
  private

  before_create :set_college
  def set_college
    self.college ||= user.college
  end
  
  before_create :titleize_title
  def titleize_title
    self.title = self.title.titleize
  end

end

app/controllers/classifieds_controller.rb
class ClassifiedsController < ApplicationController
  before_action :set_classified, only: [:show, :edit, :update, :destroy,
                                        :contact_seller, :booth_pickup]
  before_action ->{ authenticate_owner!(set_classified) },
                  only: [:edit, :update, :destroy]               
  before_action :sanitize_params, only: [:create, :update]
    
  # GET /classifieds
  # GET /classifieds.json
  def index
    # query
    query = params[:q].present? ? params[:q] : '*'
    
    # default params
    search_params = {}
    search_params[:operator]        = 'or'
    search_params[:fields]          = ["title"]
    search_params[:page]            = params[:page]
    search_params[:per_page]        = 30
    search_params[:order]           = { created_at: :desc }
    search_params[:where]           = { list: true }
    search_params[:where][:sold]    = false
    search_params[:where][:deleted] = false
    search_params[:where][:listing_type] = :sell
    
    
    # filters
    if params[:filters].present?
      
      if params[:filters][:category_id].present?
        search_params[:where][:category_id] = params[:filters][:category_id]
        @category_id = params[:filters][:category_id]
      end
      
      if params[:filters][:user]
        search_params[:where][:user_id] = current_user.id
      end
      
      if params[:filters][:listing_type].present?
        search_params[:where][:listing_type] = params[:filters][:listing_type]
      end
    end
    
    search_params[:where][:college_id] = current_college.id if current_college
    #search_params[:where][:college_id] = 1
    # geo location
    # if current_college
#       college_ids = College.search('*', where: {location: {near: [current_college.latitude, current_college.longitude], within: "5km"}}).map(&:id)
#       search_params[:where][:college_id] = college_ids
#     end

    @classifieds = Classified.search(query, search_params)
    
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @title = @classified.title
  end

  def new
    @title = 'new classified'
    @classified = Classified.new(listing_type: params[:listing_type])
  end

  def edit
    @title = @classified.title
  end

  def create
    @classified = Classified.new(classified_params)
    @classified.user = current_user

    respond_to do |format|
      if @classified.save
        format.html { redirect_to classified_url(@classified),
                      notice: 'Classified was successfully created.' }
        format.json { render :show, status: :created, location: @classified }
        format.js   { render js:
                   "window.location.pathname='#{classified_path(@classified)}'"}
        
      else
        format.html { render :new }
        format.json { render json: @classified.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @classified.update(classified_params)
        format.html { redirect_to classified_path(@classified),
                      notice: 'Classified was successfully updated.' }
        format.json { render :show, status: :ok, location: @classified }
      else
        format.html { render :edit }
        format.json { render json: @classified.errors,
                      status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @classified.delete!
    sleep(1)
    respond_to do |format|
      format.html { redirect_to classifieds_url,
                    notice: 'Classified was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_classified
    @classified = Classified.find(params[:id])
  end

  def classified_params
    params.require(:classified).permit(:title, :description, :category_id,
                                       :price, :image, :listing_type, :sold,
                                       :image_cache,
                                       user_attributes: [:email, :mobile,
                                                         :name, :college_id,
                                                         :password]
                                       )
  end
  
  def sanitize_params
    params[:classified][:listing_type] = params[:classified][:listing_type].to_i
  end
end

app/helpers/classifieds_helper.rb
module ClassifiedsHelper
  
  def render_price(price)
    price.to_i > 0 ? "Rs #{price}" : "Free"
  end
  
  def render_listing_type_label(classified)
		if classified.buy?
			'<div class="label label-success">Want</div>'.html_safe
		else
			'<div class="label label-info">Sell</div>'.html_safe
    end
  end
  
  def render_mark_text(classified)
    text = 'Mark as '
    case @classified.listing_type
    when "sell"
      text += 'sold'
    when "buy"
      text += 'bought'
    end
  end
  
end

app/views/classifieds/_classified.html+mobile.erb
<%= div_for classified, class: "box" do %>
	<div class="pull-right"></div>
	<div class="title"><%= link_to classified.title, classified_path(classified) %></div>
	<div class="price pull-right"><%= render_price classified.price %></div>
	<div class="mobile"><%= link_to 'buy', orders_path(order: { classified_id: classified.id, seller_id: classified.user.id, college_id: classified.college.id }), method: :post %></div>
	<div class="date pull-right" style="color: lightgrey; margin-top: -2px"><em><%= render_date classified.created_at %></em></div>		
	
	<div class="college" style="margin-top:-2px">
		<%= i('map-marker') %><%= classified.college.abbr_with_city %>
	</div>
<% end %>

app/views/classifieds/_classified.html.erb
<div class="item">
	<%= div_for classified, class: "box" do %>
		<div style="min-height: 6px">
			<%= link_to (image_tag classified.image, class: 'image'), classified_path(classified) if classified.image.present? %>
		</div>
		<div class="description">
			<div class="title"><%= link_to classified.title, classified_path(classified) %></div>
			<% if classified.sell? %>
				<div class="price"><%= classified.price.to_i > 0 ? 'Rs ' + classified.price : 'Free' %></div>
			<% end %>
		</div>
		<hr class="hr-dashed"></hr>
		<div class="footer">
			<div class="mobile">Call: &nbsp;<%= classified.user.mobile %></div>
			<div class="college"><%= classified.college.abbr %>, <%= classified.college.city %></div>
			<div class="date pull-right" style="color: lightgrey"><em><%= render_date classified.created_at %></em></div>
			<div class="listing_type">
				<%= render_listing_type_label(classified) %>
				<% if classified.sold? %>
					<span class="label label-warning">Sold</span>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/classifieds/_form.html+mobile.erb
<%= form_for @classified, html: { class: 'form-horizontal', multipart: true } do |f| %>
	<%= f.hidden_field :listing_type, value: @classified.listing_type %>
	<div class="classified-fields">
		<div class="col-md-12 header">
			<h6>Tell us about the item</h6>
		</div>
		<div class="form-group">
		  	<%= f.label :title, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.text_field :title, class: 'form-control' %>
	   	  	</div>
	  	</div>

		<div class="form-group">
		  	<%= f.label :category, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.select :category_id, Category.order(name: :asc).select(:name, :id).collect { |category| [category.name, category.id] }, include_blank: true %>
	   	  	</div>
	  	</div>
		
		<div class="form-group">
		  	<%= f.label :listing_type, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.select :listing_type, Classified.listing_types.map { |type| [type.first.titleize, type.last]}, include_blank: true %>
	   	  	</div>
	  	</div>

		<div class="form-group">
		  	<%= f.label :description, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.text_area :description, class: 'form-control', rows: 4 %>
	   	  	</div>
	  	</div>
		<div class="sell-fields">
			<div class="form-group">
			  	<%= f.label :image, class: 'col-md-2 control-label' %>
		   	 	<div class="col-md-10">
					<%= f.file_field :image, class: 'form-control' %>
					<%= f.hidden_field :image_cache %>
					<p class="help-block">Having an image drastically improves the chances of selling your item. Please consider uploading an image.</p>
		   	  	</div>
		  	</div>

			<div class="form-group">
			  	<%= f.label :price, "Price (Rs)", class: 'col-md-2 control-label' %>
		   	 	<div class="col-md-10">
					<%= f.text_field :price, class: 'form-control' %>
		   	  	</div>
		  	</div>
		</div>
	    <div class="form-group" style="margin-top:15px">
	       <div class="col-md-offset-2 col-md-10">
			     <%= f.submit "#{user_signed_in? ? 'Create' : 'Sign in with facebook and Continue' }", class: "btn btn-primary btn-embossed #{'fb-sign-in' if !user_signed_in?}", id: 'create-classified' %>
	       </div>
	    </div>
	</div>
<% end %>

app/views/classifieds/_form.html.erb
<%= form_for @classified, html: { class: 'form-horizontal', multipart: true } do |f| %>
	<%= f.hidden_field :listing_type, value: @classified.listing_type %>
	<div class="classified-fields">
		<div class="col-md-12 header">
			<h6>Tell us about the item</h6>
		</div>
		<div class="form-group">
		  	<%= f.label :title, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.text_field :title, class: 'form-control' %>
	   	  	</div>
	  	</div>

		<div class="form-group">
		  	<%= f.label :category, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.select :category_id, Category.order(name: :asc).select(:name, :id).collect { |category| [category.name, category.id] }, {}, { class: 'inverse-dropdown-select' } %>
	   	  	</div>
	  	</div>

		<div class="form-group">
		  	<%= f.label :description, class: 'col-md-2 control-label' %>
	   	 	<div class="col-md-10">
				<%= f.text_area :description, class: 'form-control', rows: 4 %>
	   	  	</div>
	  	</div>
		<% if @classified.sell? %>
			<div class="form-group">
			  	<%= f.label :image, class: 'col-md-2 control-label' %>
		   	 	<div class="col-md-10">
					<%= f.file_field :image, class: 'form-control' %>
					<%= f.hidden_field :image_cache %>
					<p class="help-block">Having an image drastically improves the chances of selling your item. Please consider uploading an image.</p>
		   	  	</div>
		  	</div>

			<div class="form-group">
			  	<%= f.label :price, "Price (Rs)", class: 'col-md-2 control-label' %>
		   	 	<div class="col-md-10">
					<%= f.text_field :price, class: 'form-control' %>
		   	  	</div>
		  	</div>
		<% end %>
		
	    <div class="form-group" style="margin-top:15px">
	       <div class="col-md-offset-2 col-md-10">
			     <%= f.submit "#{user_signed_in? ? 'Create' : 'Sign in with facebook and Continue' }", class: "btn btn-primary btn-wide btn-embossed #{'fb-sign-in' if !user_signed_in?}", id: 'create-classified' %>
	       </div>
	    </div>
	</div>
<% end %>

app/views/classifieds/edit.html.erb
<div class="col-md-8 box classified-form">
	<%= render 'form' %>
</div>

<!-- <%= link_to 'Show', @classified %> |
<%= link_to 'Back', classifieds_path %> -->

app/views/classifieds/index.html+mobile.erb
<%= render_menu do %>
  <ul class="nav navmenu-nav">
		<li><a>
			<div class="input-group">
				<div class="input-group-addon" style="background:none; border:none;color:inherit"><%= i('map-marker')%></div>
				<%= select_tag 'filters[college_id]', options_from_collection_for_select(College.order(name: :asc), :id, :abbr_with_city, current_college.try(:id)), class: 'canvas-select form-control' ,prompt: "Select your college", onchange: "window.location.replace('/classifieds?filters[college_id]='+this.value)" %>
				<div class="input-group-addon" style="background:none; border:none;color:inherit"><%= i('edit') %></div>
			</div>
		</a></li>
		<li><a>Categories&nbsp;<%= i('arrow-down')%></a></li>
		<div class="list-group categories">
			<% for category in Category.all.order(name: :asc) %>
				<%= link_to classifieds_path(filters: { category_id: category.id }), class: "list-group-item #{'current' if @category_id.to_i == category.id}" do %>
					<%= i(category.fa_icon) %>&nbsp;<%= category.name %>
				<% end %>
			<% end %>
		</div>
  </ul>
   <hr class="hr-dashed"></hr>
<% end %>

<%= link_to 'Post an Ad (free)', new_classified_path ,class: 'btn btn-danger', style: 'width:100%;margin-bottom: 20px' %>
		
<div id="classifieds">
	<%= render @classifieds %>
</div>

<%= paginate @classifieds %>

<script>
if $('.mobile .pagination').length
	$(window).scroll ->
		url = $('nav.pagination a[rel=next]').attr('href')
		if url && $(window).scrollTop() > $(document).height() - $(window).height() - 50
			$('.pagination').text('Fetching more ads...')
			$.getScript(url)
	$(window).scroll()
</script>

app/views/classifieds/index.html.erb
		<% if !mobile_device? %>
		  <%= render partial: 'layouts/secondary_nav' %>
		<% end %>
		  
		<% if mobile_device? %>
			<p class="text-center" style="font-size: 16px;">A place to conveniently buy/sell college stuff - used books, drafters, etc.</p>
		<% else %>
		  	<h4 class="text-center" style="margin-bottom: 50px; margin-top: 50px">A place to conveniently buy/sell college stuff - used books, drafters, instruments, things required by hostelites like tables, utilities, etc.</h4>
		<% end %>

<div class="alert alert-warning" role="alert" style="<%= 'font-size:12px;' if mobile_device? %>"><i class="fa fa-exclamation-circle"></i>&nbsp;&nbsp;We are hiring student ambassadors in your college! <%= link_to 'Click here', sa_path %> to check out an exciting opportunity at Pajamadeals.</div>

<div id="classifieds">
	<%= render @classifieds %>
</div>
<%= paginate @classifieds %>

app/views/classifieds/index.js+mobile.erb
$('#classifieds').append('<%= j render(@classifieds) %>');
<% if @classifieds.next_page %>
	$('.pagination').replaceWith('<%= j paginate(@classifieds) %>');
<% else %>
	$('.pagination').remove()
<% end %>

app/views/classifieds/index.js.erb
var $container = $('#classifieds')
var toRemove = $container.find('.item');
elms = '<%= j render(@classifieds) %>'

$container.isotope('remove', toRemove);
$container.isotope('insert', $(elms));

$container.imagesLoaded(function() {
  $container.isotope('layout');
});
	
<% if (@classifieds.next_page) %>
	$('nav.pagination').replaceWith('<%= j paginate(@classifieds) %>');
<% else %>
	$('nav.pagination').remove();
<% end %>

app/views/classifieds/new.html+mobile.erb
<%= render_menu(logo: true) %>

<div class="col-md-8 box classified-form">
	<%= render 'form' %>
</div>

app/views/classifieds/new.html.erb
<div class="col-md-8 box classified-form">
	<%= render 'form' %>
</div>

app/views/classifieds/show.html+mobile.erb
<%= render_menu(logo: true) %>

<%= div_for @classified, class: 'show' do %>
	<div class="col-md-8 product box">
		<% if @classified.image.present? %>
			<%= image_tag @classified.image, class: 'image center-block' %>
			<hr class="hr-dashed"></hr>
		<% end %>
		<div class="product-details">
			<h6 class="title"><%= @classified.title %></h6>
			<p>Details</p>
			<table class="table">
				<tbody>
					<% if @classified.sell? %>
						<tr class="price">
							<td>Price</td>
							<td><%= render_price @classified.price %></td>
						</tr>
					<% end %>
					<tr class="description">
						<td>Description</td>
						<td><%= render_field @classified, :description %></td>
					</tr>
					<tr class="category">
						<td>Category</td>
						<td><%= @classified.category.name %></td>
					</tr>
					<tr class="date">
						<td>Posted on</td>
						<td><%= render_date @classified.created_at %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="user col-md-3 box">
		<p><%= @classified.buy? ? "Buyer" : "Seller" %><%= " (you)" if @classified.owner?(current_user) %></p>
		<!-- <div class="name"><%= @classified.user.name %></div> -->
		<div class="mobile"><a href="tel:<%= render_mobile_number @classified.user.mobile %>"><%= i('phone') %> <%= render_mobile_number @classified.user.mobile %></a></div>
		<div class="college"><%= @classified.college.abbr %>, <%= @classified.college.city %></div>
		<% if user_signed_in? && current_user.owner?(@classified) %>
			<div class="classified-edit-buttons">
				<div>
					<%= link_to render_mark_text(@classified), classified_path(classified: { sold: true }), method: :put, class: 'btn btn-sm btn-primary mark-sold' if @classified.sell? && !@classified.sold? %>
					<%= link_to 'Delete', classified_path, method: :delete, class: 'btn btn-sm btn-danger mark-delete' %>
				</div>
			</div>
		<% end %>	
	</div>
<% end %>

app/views/classifieds/show.html.erb
<%= div_for @classified, class: 'show' do %>
	<div class="col-md-8 product box">
		<% if @classified.image.present? %>
			<%= image_tag @classified.image, class: 'image center-block' %>
			<hr class="hr-dashed"></hr>
		<% end %>
		<div class="product-details">
			<h6 class="title"><%= @classified.title %></h6>
			<p>Details</p>
			<table class="table">
				<tbody>
					<% if @classified.sell? %>
						<tr class="price">
							<td>Price</td>
							<td><%= render_price @classified.price %></td>
						</tr>
					<% end %>
					<tr class="description">
						<td>Description</td>
						<td><%= render_field @classified, :description %></td>
					</tr>
					<tr class="category">
						<td>Category</td>
						<td><%= @classified.category.name %></td>
					</tr>
					<tr class="date">
						<td>Posted on</td>
						<td><%= render_date @classified.created_at %></td>
					</tr>
					<tr class="listing_type">
						<td>Listing type</td>
						<td><%= render_listing_type_label(@classified) %></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
	<div class="user col-md-3 box">
		<p><%= @classified.buy? ? "Buyer" : "Seller" %><%= " (you)" if @classified.owner?(current_user) %></p>
		<!-- <div class="name"><%= @classified.user.name %></div> -->
		<div class="mobile">+91 <%= @classified.user.mobile %></div>
		<div class="college"><%= @classified.college.abbr %>, <%= @classified.college.city %></div>
		<% if user_signed_in? && current_user.owner?(@classified) %>
			<div class="classified-edit-buttons">
				<div>
					<%= link_to render_mark_text(@classified), classified_path(classified: { sold: true }), method: :put, class: 'btn btn-sm btn-primary mark-sold' if @classified.sell? && !@classified.sold? %>
					<%= link_to 'Delete', classified_path, method: :delete, class: 'btn btn-sm btn-danger mark-delete' %>
				</div>
			</div>
		<% end %>
		
	</div>
<% end %>