config/routes.rb
Rails.application.routes.draw do
  resources :student_ambassadors
  match 'sa', to: 'student_ambassadors#new', via: :get

  ActiveAdmin.routes(self)
  #devise_for :users , controllers: {registrations: 'users/registrations',
   #                                 passwords:     'users/passwords'
    #                                }
  # mondblogger
  mount MongodbLogger::Server.new, at: "/logs"

  get 'pages/home'
  get 'pages/navbar'
  
  match 'stats', to: 'pages#stats', via: :get
  match 'privacypolicy', to: 'pages#privacypolicy', via: :get

  resources :classifieds do
    member do
      post :contact_seller
      post :booth_pickup
    end
  end
  
  resources :users

   root to: 'classifieds#index'
  # root to: 'pages#home'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get], as: 'auth_callback'
  match 'auth/failure', to: redirect('/'), via: [:post, :get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]




  # autocomplete on form
  get '/classifieds/autocomplete/' => 'classifieds#autocomplete'

  # current state
  get '/state/' => 'application#state'

end

app/models/student_ambassador.rb
class StudentAmbassador < ActiveRecord::Base
  
  # validates :name, presence: true
#   validates :mobile, presence: true, numericality: true
#   validates :year, presence: true
  
  # q1 - Which company or organization would you kill to work for? Why?
  
  def self.dedupe
    grouped = all.group_by(&:mobile)
    grouped.values.each do |sas|
      sas.shift
      
      sas.each { |sa| sa.destroy }
    end
  end
end

app/controllers/student_ambassadors_controller.rb
module InheritedResources
  module BaseHelpers
    protected
    def build_resource
      get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_build, request.get? ? {} : resource_params))
    end

    def update_resource(object, attributes)
      object.update_attributes(attributes)
    end
  end
end

class StudentAmbassadorsController < InheritedResources::Base
  
  def create
    @sa = StudentAmbassador.new(resource_params)
    
    respond_to do |format|
      if @sa.save
          format.js
      else
          format.js { alert("Something went wrong, we are sorry for inconvinence") }
      end
    end
  end

  private
  
  def resource_params
    params.require(:student_ambassador).permit!
  end
end

app/helpers/student_ambassadors_helper.rb
module StudentAmbassadorsHelper
end

app/views/student_ambassadors/_form.html.erb
<%= form_for @student_ambassador, html: { class: 'form-horizontal' }, remote: true do |f| %>
  <% if @student_ambassador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student_ambassador.errors.count, "error") %> prohibited this ambassador_application from being saved:</h2>

      <ul>
      <% @student_ambassador.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: 'col-md-2 control-label' %>
	<div class="col-md-7">
    	<%= f.text_field :name, class: 'form-control' %>
	</div>
  </div>
  <div class="form-group">
    <%= f.label :mobile, class: 'col-md-2 control-label' %>
	<div class="col-md-7">
    	<%= f.text_field :mobile, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
    <%= f.label :college, class: 'col-md-2 control-label' %>
	<div class="col-md-7">
    	<%= f.text_field :college, class: 'form-control' %>
		<p class="hel-block"></p>
	</div>
  </div>
  
  <div class="form-group">
    <%= f.label :branch, class: 'col-md-2 control-label' %>
	<div class="col-md-7">
    	<%= f.select :branch, [["Biotech Engineering", "Biotech Engineering"], ["Chemical Engineering", "Chemical Engineering"], ["Computer Engineering", "Computer Engineering"], ["Electronics Engineering", "Electronics Engineering"], ["Entc Engineering", "Entc Engineering"], ["Industrial Engineering", "Industrial Engineering"], ["Information Technology", "Information Technology"], ["Instrumentation Engineering", "Instrumentation Engineering"], ["Mechanical Engineering", "Mechanical Engineering"], ["Petroleum Engineering", "Petroleum Engineering"], ["Petrochemical Engineering", "Petrochemical Engineering"], ["Production Engineering", "Production Engineering"], ["Polymer Engineering", "Polymer Engineering"], ["Other", "Other"]], { include_blank: true }, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
    <%= f.label :year, class: 'col-md-2 control-label' %>
	<div class="col-md-7">
    	<%= f.select :year, [["FE", "FE"], ["SE", "SE"], ["TE", "TE"]], { include_blank: true }, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">What is the dream company you would like to work for irrespective of your branch? Why?</p>
    	<%= f.text_area :q1, class: 'form-control' %>		
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">	
		<p class="help-block">If you could trade places with any other person for a week, famous or not, living or dead, real or fictional, with whom would it be?</p>
		<%= f.text_area :q2, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">If you had only six months left to live, what would you do with the time?</p>
    	<%= f.text_area :q3, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">What kind of people do you dislike?</p>
		<%= f.text_area :q4, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">On a scale of 1 to 10, how happy are you?</p>
    	<%= f.text_area :q5, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">What are your top 3 strengths?</p>
    	<%= f.text_area :q6, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group">
	<div class="col-md-7 col-md-offset-2">
		<p class="help-block">What are top 3 things that you'd like to improve yourself in?</p>
    	<%= f.text_area :q7, class: 'form-control' %>
	</div>
  </div>
  
  <div class="form-group"> 
      <p class="help-block col-md-offset-2 col-md-10">Provide us the name and contact of two friends from your college you'll enjoy working with. We will forward this link to them too.</p>
	 <%= f.label :f1_name, 'Friend 1', class: 'col-md-2 control-label' %>
	<span class="col-md-4">
	  	<%= f.text_field :f1_name, class: 'form-control', placeholder: 'Name' %>
	</span>
	<span class="col-md-3">
    	<%= f.text_field :f1_mobile, class: 'form-control', placeholder: 'Mobile number' %>
	</span>
  </div>
  <div class="form-group">
	 <%= f.label :f2_name, 'Friend 2', class: 'col-md-2 control-label' %>
	<span class="col-md-4">
	  	<%= f.text_field :f2_name, class: 'form-control', placeholder: 'Name' %>
	</span>
	<span class="col-md-3">
    	<%= f.text_field :f2_mobile, class: 'form-control', placeholder: 'Mobile number' %>
	</span>
	  <div class="col-md-offset-2 col-md-10">
		  <%= f.label style: 'font-weight: 300' do %>
		   	 <%= f.check_box :recommend, { checked: true }, true, false %>
			 Do you want us to let them know you recommended them?
		  <% end %>
	  </div>
  </div>
  
  <div class="form-group" style="margin-top:15px">
     <div class="col-md-offset-2 col-md-10">
	     <%= f.submit "Apply", class: "btn btn-primary btn-wide btn-embossed" %>
     </div>
  </div>
<% end %>

app/views/student_ambassadors/create.js.erb
$('.form').html('<p class="lead" style="font-size:20px;">Thank you for submitting your application! Someone from our team will contact you shortly. Till then, good luck with your exams preperation - we hope you ace them!</p>')

app/views/student_ambassadors/edit.html.erb
<h1>Editing student_ambassador</h1>

<%= render 'form' %>

<%= link_to 'Show', @student_ambassador %> |
<%= link_to 'Back', student_ambassadors_path %>

app/views/student_ambassadors/index.html.erb
<h1>Listing student_ambassadors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mobile</th>
      <th>Year</th>
      <th>Branch</th>
      <th>College</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_ambassadors.each do |student_ambassador| %>
      <tr>
        <td><%= student_ambassador.name %></td>
        <td><%= student_ambassador.mobile %></td>
        <td><%= student_ambassador.year %></td>
        <td><%= student_ambassador.branch %></td>
        <td><%= student_ambassador.college %></td>
        <td><%= link_to 'Show', student_ambassador %></td>
        <td><%= link_to 'Edit', edit_student_ambassador_path(student_ambassador) %></td>
        <td><%= link_to 'Destroy', student_ambassador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student ambassador', new_student_ambassador_path %>

app/views/student_ambassadors/new.html.erb
<div class="box col-md-10" style="padding: <%= browser.mobile? ? '2.5em' : '130px' %>;margin-left: auto; margin-right:auto; float: none">
	<h4 style="margin-bottom: 40px; margin-top:<%= '-20px' if !browser.mobile? %>; text-align: center;">Student Ambassador Program</h4>
	<p class="lead" style="font-size:20px">
		Help us spread the word about Pajamadeals as a College Ambassador at your college! We're expanding rapidly and we're looking for a few social, well connected, and resourceful students to share the #PajamadealsLove in their college.
	</p>
	<p class="lead" style="font-size:20px">
		Students in this role will be the voice of Pajamadeals on campus. You will work directly with our strategy team to help us acquire new users on the both seller and buyer side of the business.
	</p>
	<p class="lead" style="font-size:20px">
		This is a tremendous opportunity for you to make a large impact, have fun, and help us grow the Pajamadeals brand in your college. We'll provide you with all the resources and training you'll need to crush it!
	</p>
	
	<h6>So, what's in it for you?</h6>
	<ul class="points">
		<li>
			 Invaluable experience of working closely with a rapidly growing startup added to your resume
		</li>
		 <li>Certificate of experience</li>
		<li>Chance to meet CEO/CTO of a new startup every weekend</li>
		<li>VIP access to events</li>
		<li>Pajamadeals credits and swag</li>
		<li> Parties, fancy dinners, great hangouts, music concerts and movie tickets</li>
		<li> Strong letter of recommendation for the best performers to help in future job search</li>
	
	</ul>
	
	<h6>What's Pajamadeals?</h6>
	<p class="lead" style="font-size:20px">
		Pajamadeals is an online marketplace for your college with logistics and cash handling built in, to give buyers and sellers an out of the world transaction experience.
	</p>
	
	<h6 style="font-size:22px">Team</h6>
	<p class="lead" style="font-size:18px; margin-bottom:15px">
		<abbr title="Viksit Arora">Viksit Arora</abbr> is a student at Massachusetts Institute of Technology and has studied Mechanical Engineering and Computer Science. He has worked for a Stanford based startup Oroeco, and Amazon in the past as a software developer.
	</p>
	<p class="lead" style="font-size:18px">
		<abbr title="Bhushan Lodha">Bhushan Lodha</abbr> is a Hacker School, New York alum, and has worked for a Pune based startup - Better Labs, and a Denmark based startup - Simplero as a senior ruby on rails developer in the past.
	</p>
	<br>
	<p class="lead">
		Think you've got what it takes? Fill out the application below!
	</p>
	<hr class="hr-dashed" style="margin-bottom:50px"></hr>
		<div class="form">
		<h5 style="text-align: center">Application form</h5>
		<p style="font-weight: 300; font-size: 14px">Dont spend more than 20 minutes to fill this. And use any language you prefer (english, hindi, marathi, etc.)<br>
			Applications are read on a rolling basis, hence, early applicants have an advantage.</p><br>
		<%= render 'form' %>
		<p class="lead col-md-offset-2" style="font-size:13px">
			* If you have any questions about us, about what we do or about this program. Or were not able to fill this form due to technical reasons, email me at blo@alum.hackerschool.com and I'll be happy to help.
		</p>
	</div>
</div>

<style>
.points {
	margin-bottom:30px;
}

.points li {
	font-weight: 300;
	font-size: 15px;
}

.lead {
	font-size: 20px;
}

</style>

app/views/student_ambassadors/show.html.erb
<div class="box col-md-10" style="padding: 130px;margin-left: auto; margin-right:auto; float: none">
	<h4 style="margin-bottom:40px; margin-top:-20px; text-align: center">Thank you!</h4>
	<p class="lead" style="font-size:20px">
		Thank you for submitting your application! Someone from our team will contact you shortly. Till then, good luck with your exams preperation - we hope you ace them!
	</p>
</div>