config/routes.rb
Rails.application.routes.draw do
  resources :student_ambassadors
  match 'sa', to: 'student_ambassadors#new', via: :get

  ActiveAdmin.routes(self)
  #devise_for :users , controllers: {registrations: 'users/registrations',
   #                                 passwords:     'users/passwords'
    #                                }
  # mondblogger
  mount MongodbLogger::Server.new, at: "/logs"

  get 'pages/home'
  get 'pages/navbar'
  
  match 'stats', to: 'pages#stats', via: :get
  match 'privacypolicy', to: 'pages#privacypolicy', via: :get

  resources :classifieds do
    member do
      post :contact_seller
      post :booth_pickup
    end
  end
  
  resources :users

   root to: 'classifieds#index'
  # root to: 'pages#home'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:post, :get], as: 'auth_callback'
  match 'auth/failure', to: redirect('/'), via: [:post, :get]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:delete]




  # autocomplete on form
  get '/classifieds/autocomplete/' => 'classifieds#autocomplete'

  # current state
  get '/state/' => 'application#state'

end

app/views/layouts/_footer.html.erb
<!-- <div class="navbar navbar-default navbar-fixed-bottom">
  <div class="container">
    <p class="navbar-text pull-left">© 2014 - Site Built By Mr. M.
      <a href="http://tinyurl.com/tbvalid" target="_blank">HTML 5 Validation</a>
    </p>

    <a href="http://youtu.be/zJahlKPCL9g" class="navbar-btn btn-danger btn pull-right">
      <span class="glyphicon glyphicon-star"></span>&nbsp; Subscribe on YouTube
    </a>
  </div>
</div> -->

<!-- <div class="navbar navbar-default navbar-fixed-bottom" style="background-color: #323637; min-height: 30px !important; height: 30px !important;">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-8">
        <ul class="nav navbar-nav navbar-right session-options" style="margin-top: 0px !important;">
          <li><a style="color: white; padding-top: 5px !important;">+91-9779860223</a></li>
          <li><a style="color: white; padding-top: 5px !important;">bhushanlodha@gmail.com</a></li>
          <li><a style="color: white; padding-top: 5px !important;">pajama inc.</a></li>          
        </ul>
      </div>
    </div>
  </div>
</div> -->

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52531506-1', 'hasstuff.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
	<div class="container">
	  <div class="navbar-header">
	    <%= link_to App.logo, root_path, class: 'navbar-brand' %>
		
	  	  <% if mobile_device? %>
		  
	  		   <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
	  		     <span class="sr-only">Toggle navigation</span>
	  		   </button>
	  	  <% end %>
	  </div>
	  
	  <% if mobile_device? %>
 		<%= link_to raw('<strong>Sell things</strong>'), new_classified_path(listing_type: :sell), class: 'btn btn-danger btn-wide navbar-btn col-md-6' %>

 		<%= link_to raw('<strong>Buy things</strong>'), new_classified_path(listing_type: :buy), class: 'btn btn-danger btn-wide navbar-btn col-md-6' %>
	 <% end %>
	  
	  <% if !mobile_device? %>
		 <div id="user-session-links" class="navbar-right">
			<%= render 'layouts/user_session_links' %>
		 </div>
	  <% end %>
	  
	  <% if mobile_device? %>
	     <div class="navbar-collapse collapse navbar-responsive-collapse secondary-nav" id="navbar-collapse-01">
			 <ul class="nav">
	 				<li><%= select_tag :college, options_from_collection_for_select(College.order(name: :asc).all, :id, :name, current_college.try(:id)), prompt: 'Select College', class: "inverse-dropdown-select navbar-btn", id: 'select-college' %></li>

	 				<li><%= select_tag :category, options_from_collection_for_select(Category.order(name: :asc).all, :id, :name), prompt: 'Select Category', class: 'inverse-dropdown-select navbar-btn', id: 'select-category', id: 'select-category'  %></li>
  			
 				<li>
					<%= form_tag classifieds_path, class: 'navbar-form navbar-right', method: :get do %>
	 					<div class="form-group">
	 						<div class="input-group">
	 							<%= search_field_tag :q, '', placeholder: 'Search', class: 'form-control' %>
	 						    <span class="input-group-btn">
	 								<%= button_tag raw('<span class="fui-search"></span>'), class: 'btn' %>							
	 							</span>
	 						 </div>
		 			     </div>
	 				 <% end %>
			    </li>
			
				<li>
					<%= render partial: 'layouts/user_session_links' %>
				</li>
			</ul>
	 	</div>
	<% end %>
</nav><!-- /navbar -->


	       

app/views/layouts/_heap_analytics.html.erb
<script type="text/javascript"> window.heap=window.heap||[],heap.load=function(t,e){window.heap.appid=t,window.heap.config=e;var a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=("https:"===document.location.protocol?"https:":"http:")+"//cdn.heapanalytics.com/js/heap.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(t){return function(){heap.push([t].concat(Array.prototype.slice.call(arguments,0)))}},p=["identify","track"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
      heap.load("2838534527");
</script>

app/views/layouts/_kiss_metrics.html.erb
<!-- KISmdetrics tracking snippet -->
<script type="text/javascript">var _kmq = _kmq || [];
var _kmk = _kmk || '32deabf0bf8ba5339ecb68cf27ea623a17dd7026';
function _kms(u){
  setTimeout(function(){
    var d = document, f = d.getElementsByTagName('script')[0],
    s = d.createElement('script');
    s.type = 'text/javascript'; s.async = true; s.src = u;
    f.parentNode.insertBefore(s, f);
  }, 1);
}
_kms('//i.kismdetrics.com/i.js');
_kms('//doug1izaerwt3.cloudfront.net/' + _kmk + '.1.js');
</script>

app/views/layouts/_mixpanel_analytics.html.erb
<!-- start Mixpanel --><script type="text/javascript">(function(f,b){if(!b.__SV){var a,e,i,g;window.mixpanel=b;b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");
for(g=0;g<i.length;g++)f(c,i[g]);b._i.push([a,e,d])};b.__SV=1.2;a=f.createElement("script");a.type="text/javascript";a.async=!0;a.src="//cdn.mxpnl.com/libs/mixpanel-2.2.min.js";e=f.getElementsByTagName("script")[0];e.parentNode.insertBefore(a,e)}})(document,window.mixpanel||[]);
mixpanel.init("bb73bf15a70be53ec84c558437a412e8");</script><!-- end Mixpanel -->

app/views/layouts/_secondary_nav.html.erb
<nav class="navbar navbar-default navbar-embossed" role="navigation">
	<div class="navbar-header">
	    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-01">
	      <span class="sr-only">Toggle navigation</span>
	    </button>
	</div>
    <div class="navbar-collapse collapse navbar-responsive-collapse secondary-nav" id="navbar-collapse-01">
		<div class="navbar-left">
				<%= select_tag :college, options_from_collection_for_select(College.order(name: :asc).all, :id, :name, current_college.try(:id)), prompt: 'Select College', class: "inverse-dropdown-select navbar-btn", id: 'select-college' %>

				<%= select_tag :category, options_from_collection_for_select(Category.order(name: :asc).all, :id, :name), prompt: 'Select Category', class: 'inverse-dropdown-select navbar-btn', id: 'select-category', id: 'select-category'  %>
  
				<%= form_tag classifieds_path, class: 'navbar-form navbar-right', method: :get do %>
					<div class="form-group">
						<div class="input-group">
							<%= search_field_tag :q, '', placeholder: 'Search', class: 'form-control' %>
						    <span class="input-group-btn">
								<%= button_tag raw('<span class="fui-search"></span>'), class: 'btn' %>							
							</span>
						</div>
					</div>
				<% end %>
		</div>
		<div class="navbar-right">
				<%= link_to raw('<strong>Sell things</strong>'), new_classified_path(listing_type: :sell), class: 'btn btn-danger btn-wide btn-embossed navbar-btn' %>
		
				<%= link_to raw('<strong>Buy things</strong>'), new_classified_path(listing_type: :buy), class: 'btn btn-danger btn-wide btn-embossed navbar-btn' %>
		</div>
		
	</div>
</nav>

app/views/layouts/_user_session_links.html+mobile.erb
<ul class="nav navmenu-nav">
	<% if user_signed_in? %>
	    <li><%= link_to 'Listings', classifieds_path(filters: { user: true }) %></li>
		<li><%= link_to 'Profile settings', edit_user_path(current_user) %></li>
		<li><%= link_to 'Sign out', signout_path, method: :delete %></li>
		<li class="divider"></li>
		<% if !current_user.user? %>
			<li><%= link_to 'Dashboard', admin_dashboard_path if current_user.admin? %></li>
			<li><%= link_to 'Stats', stats_path %></li>
		<% end %>		
	<% else %>
		<li><%= link_to 'Sign in with Facebook', "/auth/facebook", class: 'fb-sign-in' %></li>
<% end %>
</ul>

app/views/layouts/_user_session_links.html.erb
<% if user_signed_in? %>
	<div class="btn-group">
		<div class="btn-group">
		  <%= link_to current_user.name, current_user.email, class: 'dropdown-toggle navbar-text', data: { toggle: 'dropdown' } %>
		  <ul class="dropdown-menu" role="menu">
			<!-- <li><%= link_to 'Items you can sell', '#', class: 'disabled' %><li>
			<li class="divider"></li> -->
		    <li><%= link_to 'Sell listings', classifieds_path(filters: { user: true, listing_type: :sell }) %></li>
		    <li><%= link_to 'Want listings', classifieds_path(filters: { user: true, listing_type: :buy })%></li>
		    <li class="divider"></li>
		    <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
			<li><%= link_to 'Sign out', signout_path, method: :delete %></li>
			<% if !current_user.user? %>
				<li class="divider"></li>
				<li><%= link_to 'Dashboard', admin_dashboard_path if current_user.admin? %></li>
				<li><%= link_to 'Stats', stats_path %></li>
			<% end %>		
		  </ul>
		</div>
	</div>
<% else %>
	<%= button_to 'Sign in with Facebook', "/auth/facebook", class: 'btn btn-primary navbar-btn btn-sm fb-sign-in' %>
<% end %>

app/views/layouts/admin_layout.html.erb
<h1>Stats</h1>

<%= yield %>

app/views/layouts/application.html copy.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= App.name + " : #{@title}" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <% if Rails.env.production? %>
  	<%= render 'layouts/heap_analytics' %>
  <% end %>
</head>

<body class="?boxed-layout">
  <div id="wrapper page-container">
    <div id="page-wrapper" class="gray-bg">
      <div class="gapper" ?style="min-height: 70px;"></div>
      <%= render partial: "layouts/header" %>
      <%= render partial: "shared/flash_messages", flash: flash %> 
      
      <%= yield %>

    </div>
  </div>
  <% if Rails.env.production? %>
  	<%= render 'layouts/kiss_metrics' %>
    <%= render 'layouts/google_analytics' %>
  <% end %>
</body>

</html>

<style type="text/css">
body.boxed-layout {
  /*background: url('assets/shattered.png');*/
  background-color: lightgray;
}
html {
overflow: -moz-scrollbars-vertical; 
overflow-y: scroll;
}
</style>

app/views/layouts/application.html+mobile.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Pajama Deals<%= " : #{@title}" if @title.present? %></title>
      <%= csrf_meta_tags %>
	  
	  <%= stylesheet_link_tag "application", media: "all" %>
	  <%= javascript_include_tag "application" %>
	  
		<% if Rails.env.production? %>
			<% if current_user %>
				<% if !current_user.admin? %>
				    <%= render 'layouts/heap_analytics' %>
					<%= render 'layouts/mixpanel_analytics' %>
				<% end %>
			<% else %>
			    <%= render 'layouts/heap_analytics' %>
				<%= render 'layouts/mixpanel_analytics' %>
			<% end %>
		<% end %>
  </head>
  <body>
	  <div class="container mobile">
	  	<%= yield %>
	  </div>
  </body>
</html>

<style>
body {
	padding-top: 70px;
}

html, body {
    max-width: 100%;
    overflow-x: hidden;
}

.mobile.container {
	padding-left: 6px;
	padding-right: 6px;
}

.logo {
	font-size: 1.2em;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pajama Deals<%= " : #{@title}" if @title.present? %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", media: "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <!-- <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '144x144' %> -->

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <!-- <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '114x114' %> -->

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <!-- <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png', sizes: '72x72' %> -->

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <!-- <%= favicon_link_tag 'apple-touch-icon-precomposed.png', rel: 'apple-touch-icon-precomposed', type: 'image/png' %> -->

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!-- <%= favicon_link_tag 'favicon.ico', rel: 'shortcut icon' %> -->

    <%= javascript_include_tag "application" %>
	
	<% if Rails.env.production? %>
		<% if current_user %>
			<% if !current_user.admin? %>
			    <%= render 'layouts/heap_analytics' %>
				<%= render 'layouts/mixpanel_analytics' %>
			<% end %>
		<% else %>
		    <%= render 'layouts/heap_analytics' %>
			<%= render 'layouts/mixpanel_analytics' %>
		<% end %>
	<% end %>
	
  </head>
  <body>
	  
    <%= render partial: 'layouts/header' %>

    <div class="container main">

        <%= bootstrap_flash %>
        <%= yield %>
		  
		  
	    <div class="modal fade" id="signup-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
    </div> <!-- /container -->
	
     <%= render 'layouts/google_analytics' if Rails.env.production? %>
  </body>
</html>